# This workflow builds the HoMi snakefile DAG and colors 
name: DAG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    name: DAG

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build DAG
      run: snakemake --configfile tests/example_config.yaml --dag > dag.dot

    - name: Make SVG
      run: dot dag.dot -Tsvg > dag.svg

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dag
        path: dag.svg
    
    - name: Make figures directory
      run: mkdir -p figures
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dag
        path: figures/
